version: '3.9'

services:
  postgres:
    image: postgres:17-bookworm
    container_name: postgres-local
    restart: unless-stopped
    environment:
      POSTGRES_DB: remito_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-local
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - backend

  redis:
    image: redis:8.4
    restart: on-failure
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data


volumes:
  postgres_data:
  redis_data:

networks:
  backend:
    driver: bridge
