services:
  postgres:
    image: postgres:17-bookworm
    container_name: postgres-local
    restart: unless-stopped
    environment:
      POSTGRES_DB: remito_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d remito_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-local
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - backend

  redis:
    image: redis:8.4
    restart: on-failure
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-local
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=7d'
    networks:
      - backend

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-local
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: false
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - backend

#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: remito-app
#    restart: unless-stopped
#    ports:
#      - "8080:8080"
#    environment:
#      DB_USERNAME: admin
#      DB_PASSWORD: root
#      REDIS_HOST: redis
#      REDIS_PORT: 6379
#      JWT_SECRET: ${JWT_SECRET}
#      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
#      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
#      YANDEX_CLIENT_ID: ${YANDEX_CLIENT_ID}
#      YANDEX_CLIENT_SECRET: ${YANDEX_CLIENT_SECRET}
#      FRONTEND_URL: ${FRONTEND_URL}
#      MAIL_HOST: ${MAIL_HOST}
#      MAIL_USERNAME: ${MAIL_USERNAME}
#      MAIL_PASSWORD: ${MAIL_PASSWORD}
#      ADMIN_EMAIL: ${ADMIN_EMAIL}
#    depends_on:
#      postgres:
#        condition: service_healthy
#      redis:
#        condition: service_started
#    networks:
#      - backend

volumes:
  postgres_data:
  redis_data:
  grafana_data:
  prometheus_data:

networks:
  backend:
    driver: bridge
