import { Product, Tab } from './products.types'

export const tabs: Tab[] = [
  { id: 'all',    label: 'Все товары'      },
  { id: 'laser',  label: 'Лазерные',  emoji: '🖨'  },
  { id: 'inkjet', label: 'Струйные',  emoji: '💧' },
  { id: 'drum',   label: 'Драм-картриджи', emoji: '⚙️' },
];

export const products: Product[] = [
  {
    id: 'canon-725',
    href: '/tovary/canon-725',
    category: 'laser',
    badges: [
      { type: 'hit',  label: '🔥 Хит'    },
      { type: 'orig', label: 'Оригинал'  },
    ],
    brand: 'Canon',
    title: 'Картридж Canon 725 Black',
    compat: 'Совместим с: Canon MF3010, LBP6000, LBP6020, LBP6030',
    specs: ['⚫ Чёрный', '1 600 стр.', 'Лазерный'],
    priceOld: 1200,
    price: 980,
  },
  {
    id: 'hp-85a',
    href: '/tovary/hp-85a',
    category: 'laser',
    visualBg: '#EBF5FB',
    badges: [
      { type: 'new', label: '✨ Новинка' },
    ],
    brand: 'HP',
    title: 'Картридж HP 85A (CE285A)',
    compat: 'Совместим с: HP LaserJet P1102, P1102w, M1132, M1212nf',
    specs: ['⚫ Чёрный', '1 600 стр.', 'Лазерный'],
    price: 1150,
  },
  {
    id: 'xerox-106r02773',
    href: '/tovary/xerox-106r02773',
    category: 'laser',
    visualBg: '#FEF3C7',
    badges: [
      { type: 'sale', label: '−20%' },
    ],
    brand: 'Xerox',
    title: 'Картридж Xerox 106R02773',
    compat: 'Совместим с: Xerox Phaser 3020, WorkCentre 3025',
    specs: ['⚫ Чёрный', '1 500 стр.', 'Лазерный'],
    priceOld: 1400,
    price: 1120,
  },
  {
    id: 'samsung-mlt-d101s',
    href: '/tovary/samsung-mlt-d101s',
    category: 'laser',
    visualBg: '#F0FDF4',
    badges: [
      { type: 'hit', label: '🔥 Хит' },
    ],
    brand: 'Samsung',
    title: 'Картридж Samsung MLT-D101S',
    compat: 'Совместим с: Samsung ML-2160, ML-2165, SCX-3400',
    specs: ['⚫ Чёрный', '1 500 стр.', 'Лазерный'],
    price: 890,
  },
  {
    id: 'epson-t6641',
    href: '/tovary/epson-t6641',
    category: 'inkjet',
    visualBg: '#EFF6FF',
    badges: [],
    brand: 'Epson',
    title: 'Чернила Epson T6641 Black',
    compat: 'Совместим с: Epson L100, L110, L120, L200, L210',
    specs: ['⚫ Чёрный', '70 мл', 'Струйный'],
    price: 450,
  },
  {
    id: 'canon-pg-46',
    href: '/tovary/canon-pg-46',
    category: 'inkjet',
    visualBg: '#FFF7ED',
    badges: [
      { type: 'orig', label: 'Оригинал' },
    ],
    brand: 'Canon',
    title: 'Картридж Canon PG-46 Black',
    compat: 'Совместим с: Canon PIXMA E464, E484, E414',
    specs: ['⚫ Чёрный', '400 стр.', 'Струйный'],
    price: 680,
  },
  {
    id: 'canon-drum-dr2335',
    href: '/tovary/canon-drum-dr2335',
    category: 'drum',
    visualBg: '#F5F3FF',
    badges: [],
    brand: 'Canon',
    title: 'Драм-картридж Canon DR-2335',
    compat: 'Совместим с: Canon MF113w, MF232w, MF237w',
    specs: ['⚫ Чёрный', '12 000 стр.', 'Фотобарабан'],
    price: 2100,
  },
  {
    id: 'hp-drum-cf219a',
    href: '/tovary/hp-drum-cf219a',
    category: 'drum',
    visualBg: '#F0FDF4',
    badges: [
      { type: 'new', label: '✨ Новинка' },
    ],
    brand: 'HP',
    title: 'Драм-картридж HP CF219A',
    compat: 'Совместим с: HP LaserJet Pro M102, M130',
    specs: ['⚫ Чёрный', '12 000 стр.', 'Фотобарабан'],
    price: 2450,
  },
];