spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  flyway:
    enabled: true

  data:
    redis:
#      url: ${REDIS_URL}
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
          yandex:
            client-id: ${YANDEX_CLIENT_ID}
            client-secret: ${YANDEX_CLIENT_SECRET}

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-ms: 900000
  refresh-token-expiration-ms: 2592000000

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

management:
  endpoint:
    health:
      show-details: never

app:
  frontend-url: ${FRONTEND_URL:http://localhost:3000}
  mail:
    to: ${ADMIN_EMAIL:info@ремито.рф}
  telegram:
    bot-token: ${TELEGRAM_BOT_TOKEN}
    chat-id: ${TELEGRAM_CHAT_ID}

logging:
  level:
    root: WARN