import type { Product } from './product.types'

/**
 * Примеры товаров для вёрстки и тестов.
 * Не импортировать в product.data.ts — только справочник до подключения API.
 */
export const PRODUCTS_MOCK: Product[] = [
	{
		id: 1,
		name: 'Картридж Canon 725 Black',
		slug: 'canon-725',
		description:
			'Лазерный картридж Canon 725 для принтеров Canon i-SENSYS LBP6000, LBP6020, MF3010. Ресурс 1600 страниц.',
		price: 980,
		priceOld: 1200,
		stockQuantity: 3,
		categoryName: 'Лазерный',
		categorySlug: 'laser',
		productKind: 'cartridge',
		brandName: 'Canon',
		colorName: 'Чёрный',
		colorHex: '#1a1a1a',
		pageYield: 1600,
		compatibility: 'Совместим с: Canon MF3010, LBP6000, LBP6020, LBP6030',
		imageUrl: '',
		isActive: true,
		isOriginal: true,
		badges: [
			{ type: 'hit', label: 'Хит' },
			{ type: 'original', label: 'Оригинал' }
		]
	},
	{
		id: 2,
		name: 'Картридж HP 85A (CE285A)',
		slug: 'hp-85a',
		description:
			'Лазерный картридж HP 85A для принтеров HP LaserJet P1102, P1102w, M1132, M1212nf. Ресурс 1600 страниц.',
		price: 1150,
		stockQuantity: 5,
		categoryName: 'Лазерный',
		categorySlug: 'laser',
		productKind: 'cartridge',
		brandName: 'HP',
		colorName: 'Чёрный',
		colorHex: '#1a1a1a',
		pageYield: 1600,
		compatibility: 'Совместим с: HP LaserJet P1102, P1102w, M1132, M1212nf',
		imageUrl: '',
		isActive: true,
		visualBg: '#EBF5FB',
		badges: [{ type: 'new', label: 'Новинка' }]
	},
	{
		id: 3,
		name: 'Картридж Xerox 106R02773',
		slug: 'xerox-106r02773',
		description: 'Лазерный картридж Xerox для принтеров Phaser 3020, WorkCentre 3025. Ресурс 1500 страниц.',
		price: 1120,
		priceOld: 1400,
		stockQuantity: 2,
		categoryName: 'Лазерный',
		categorySlug: 'laser',
		productKind: 'cartridge',
		brandName: 'Xerox',
		colorName: 'Чёрный',
		colorHex: '#1a1a1a',
		pageYield: 1500,
		compatibility: 'Совместим с: Xerox Phaser 3020, WorkCentre 3025',
		imageUrl: '',
		isActive: true,
		visualBg: '#FEF3C7',
		badges: [{ type: 'sale', label: '−20%' }]
	},
	{
		id: 4,
		name: 'Картридж Samsung MLT-D101S',
		slug: 'samsung-mlt-d101s',
		description: 'Лазерный картридж Samsung для принтеров ML-2160, ML-2165, SCX-3400. Ресурс 1500 страниц.',
		price: 890,
		stockQuantity: 4,
		categoryName: 'Лазерный',
		categorySlug: 'laser',
		productKind: 'cartridge',
		brandName: 'Samsung',
		colorName: 'Чёрный',
		colorHex: '#1a1a1a',
		pageYield: 1500,
		compatibility: 'Совместим с: Samsung ML-2160, ML-2165, SCX-3400',
		imageUrl: '',
		isActive: true,
		visualBg: '#F0FDF4',
		badges: [{ type: 'hit', label: 'Хит' }]
	},
	{
		id: 5,
		name: 'Чернила Epson T6641 Black',
		slug: 'epson-t6641',
		description: 'Чернила Epson T6641 для принтеров серии L100, L110, L120, L200, L210.',
		price: 450,
		stockQuantity: 8,
		categoryName: 'Струйный',
		categorySlug: 'inkjet',
		productKind: 'ink',
		brandName: 'Epson',
		colorName: 'Чёрный',
		colorHex: '#1a1a1a',
		volumeMl: 70,
		compatibility: 'Совместим с: Epson L100, L110, L120, L200, L210',
		imageUrl: '',
		isActive: true,
		visualBg: '#EFF6FF',
		badges: []
	},
	{
		id: 6,
		name: 'Картридж Canon PG-46 Black',
		slug: 'canon-pg-46',
		description: 'Струйный картридж Canon PG-46 для PIXMA E464, E484, E414. Ресурс 400 страниц.',
		price: 680,
		stockQuantity: 6,
		categoryName: 'Струйный',
		categorySlug: 'inkjet',
		productKind: 'cartridge',
		brandName: 'Canon',
		colorName: 'Чёрный',
		colorHex: '#1a1a1a',
		pageYield: 400,
		compatibility: 'Совместим с: Canon PIXMA E464, E484, E414',
		imageUrl: '',
		isActive: true,
		isOriginal: true,
		visualBg: '#FFF7ED',
		badges: [{ type: 'original', label: 'Оригинал' }]
	},
	{
		id: 7,
		name: 'Драм-картридж Canon DR-2335',
		slug: 'canon-drum-dr2335',
		description: 'Фотобарабан Canon DR-2335 для MF113w, MF232w, MF237w. Ресурс 12 000 страниц.',
		price: 2100,
		stockQuantity: 1,
		categoryName: 'Фотобарабан',
		categorySlug: 'drum',
		productKind: 'drum',
		brandName: 'Canon',
		colorName: 'Чёрный',
		colorHex: '#1a1a1a',
		pageYield: 12000,
		compatibility: 'Совместим с: Canon MF113w, MF232w, MF237w',
		imageUrl: '',
		isActive: true,
		visualBg: '#F5F3FF',
		badges: []
	},
	{
		id: 8,
		name: 'Драм-картридж HP CF219A',
		slug: 'hp-drum-cf219a',
		description: 'Фотобарабан HP CF219A для LaserJet Pro M102, M130. Ресурс 12 000 страниц.',
		price: 2450,
		stockQuantity: 2,
		categoryName: 'Фотобарабан',
		categorySlug: 'drum',
		productKind: 'drum',
		brandName: 'HP',
		colorName: 'Чёрный',
		colorHex: '#1a1a1a',
		pageYield: 12000,
		compatibility: 'Совместим с: HP LaserJet Pro M102, M130',
		imageUrl: '',
		isActive: true,
		visualBg: '#F0FDF4',
		badges: [{ type: 'new', label: 'Новинка' }]
	},
	{
		id: 9,
		name: 'Картридж Kyocera TK-1150',
		slug: 'kartridzh-kyocera-tk-1150',
		description: 'Лазерный картридж Kyocera для ECOSYS M2135dn, M2635dn, P2235dn. Ресурс 3000 страниц.',
		price: 1450,
		stockQuantity: 3,
		categoryName: 'Лазерный',
		categorySlug: 'laser',
		productKind: 'cartridge',
		brandName: 'Kyocera',
		colorName: 'Чёрный',
		colorHex: '#1a1a1a',
		pageYield: 3000,
		compatibility: 'Совместим с: Kyocera ECOSYS M2135dn, M2635dn, P2235dn',
		imageUrl: '',
		isActive: true,
		badges: [{ type: 'compat', label: 'Совместимый' }]
	}
]
